#!/bin/sh

set -eu

FLAGS=
RETRY=

if [ -f $HOME/pyston_deps/binutils-build/gold/ld-new ]; then
    LD=$HOME/pyston_deps/binutils-build/gold/ld-new
    # FLAGS="--incremental --incremental-patch=10"
    # RETRY=y
elif [ -f $HOME/pyston_deps/binutils-2.24-build/gold/ld-new ]; then
    LD=$HOME/pyston_deps/binutils-2.24-build/gold/ld-new
    # FLAGS="--incremental --incremental-patch=10"
    # RETRY=y
elif which gold > /dev/null ; then
    LD=gold
    # FLAGS="--incremental --incremental-patch=10"
    # RETRY=y
else
    echo "gold not available"
    LD=ld
fi

set +e

# echo $LD $FLAGS "$@"
$LD $FLAGS "$@"
EXIT=$?
if [ $EXIT -ne 0 -a -n "$RETRY" ]; then
    echo "retrying"
    $LD $FLAGS "$@"
    EXIT=$?
fi
exit $EXIT
